# Generated by Django 5.1.7 on 2025-03-08 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='usuario',
            new_name='cliente',
        ),
    ]
