# Generated by Django 5.1.7 on 2025-03-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='imagem_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
