# Generated by Django 5.1.7 on 2025-03-25 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='profissional',
            field=models.ForeignKey(limit_choices_to={'tipo_usuario': 'profissional'}, on_delete=django.db.models.deletion.CASCADE, related_name='servicos_oferecidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
