# Generated by Django 5.1.7 on 2025-04-10 23:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='profissionais',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tipo_usuario': 'profissional'}, related_name='servicos_oferecidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
