# Generated by Django 5.1.7 on 2025-03-28 00:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='profissional',
        ),
        migrations.AddField(
            model_name='servico',
            name='profissionais',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tipo_usuario': 'profissional'}, related_name='servicos_oferecidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
