# Generated by Django 5.1.7 on 2025-03-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='imagem_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
